var equipo1= new Array('<div class="pvillegas"></div>','Patricia Villegas', 'Presidenta de teleSUR', '<p>Patricia Villegas nació en Cali, la tercera ciudad más poblada de Colombia. Comenzó en la multiestatal de noticias como presentadora de noticias y programas informativos y es una de las fundadoras de teleSUR, actualmente es la presidenta del canal. Decidió ser periodista porque quiere cambiar el mundo."Trabajo para que sean visibles las realidades de los pueblos que no son escuchados (...) Trabajamos con pasión, con honestidad y buscando, con rigor y respeto, contar la realidad de nuestros compatriotas latinoamericanos y caribeños. Nosotros estamos en esta tierra, somos parte de ella, hacemos periodismo desde nuestra Patria Grande".</p>', '<a href="https://twitter.com/pvillegas_tlSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/pvillegas_tlSUR" target="_blank">@pvillegas_tlSUR</a>'); 

var equipo2 = new Array('<div class="aistillarte"></div>','Abraham Istillarte', 'Presentador de noticias y programas informativos', '<p>Abraham Istillarte es un periodista venezolano graduado en la Universidad del Zulia. Amplió su formación con una maestría en Estudios Latinoamericanos en la Pontificia Universidad Javeriana, en Bogotá, Colombia.Cuando escuchó a Fidel Castro y Hugo Chávez hablar sobre la necesidad de crear un medio latinoamericano, independiente y que rompiera el monopolio de las grandes transnacionales de la comunicación, procuró por todas las vías integrarse al proyecto y lo logró. "Estoy desde que éramos no más de 15 personas, la señal aún no estaba al aire. Ayudé con el lanzamiento de nuestra señal".Para Istillarte, quienes atacan a teleSUR intentan silenciar el afán de los pueblos por conquistar sus derechos, por contar su verdad.</p>', '<a href="https://twitter.com/abrahamteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/abrahamteleSUR" target="_blank">@abrahamteleSUR</a>'); 

var equipo3 = new Array('<div class="tperez"></div>','Tatiana Perez', 'Presentadora de noticias y programas informativos', '<p>Tatiana Pérez nació en Colombia y se graduó de periodista en la Universidad Autónoma de Occidente, en Cali.El deseo de contar y evidenciar historias como las del conflicto armado colombiano la llevó a formarse como comunicadora social."Trabajo en teleSUR por el corazón y la razón. Su firmeza por hacer un periodismo responsable, con rigor, apegado a la verdad y la realidad, no son principios que se encuentren fácilmente en un medio de comunicación".La guerra de la OTAN contra Libia, las liberaciones de retenidos por las Fuerzas Armadas Revolucionarias de Colombia (FARC) y el golpe de Estado contra Manuel Zelaya en Honduras, han impactado su forma de ver el mundo y ejercer el periodismo.</p>', '<a href="https://twitter.com/tatianateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/tatianateleSUR" target="_blank">@tatianateleSUR</a>'); 

var equipo4 = new Array('<div class="rgomez"></div>','Rey G&oacute;mez', 'Presentador de noticias y programas informativos', '<p>Rey Gómez es un periodista cubano y presentador de noticias en teleSUR. Es licenciado en Español y Literatura, pero eligió la comunicación social como carrera debido a la influencia de su hermano quien es periodista.La política internacional y los procesos de integración de los pueblos siempre han interesado a Gómez."Nuestra programación tiene gran aceptación. Donde quiera me identifican como presentador del canal, algunos desconocen mi nombre y cariñosamente exclaman:"¡Épale teleSUR!".</p>', '<a href="https://twitter.com/ReyGomeztlSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/ReyGomeztlSUR" target="_blank">@ReyGomeztlSUR</a>');

var equipo5 = new Array('<div class="mchirinos"></div>','Marayira Chirinos', 'Presentadora de noticias y programas informativos', '<p>Marayira Chirinos Es licenciada en Estudios Políticos egresada de la Universidad Central de Venezuela (UCV), pero ha adoptado al periodismo como su segunda profesión.Desde que escuchó en la voz del líder de la Revolución Bolivariana, Hugo Chávez y la creación de teleSUR como necesidad urgente para democratizar la comunicación en América Latina, se sintió plenamente identificada con ese proyecto."Sentí que cambiaría la historia comunicacional de la región y del mundo. Con el más grande orgullo puedo decir que lo logró, al primer intento".Considera a teleSUR como el medio que cuenta la realidad de Latinoamérica y el mundo, vista desde los ojos de los pueblos. "Un periodismo comprometido con las historias locales, las que nadie más contaba". En sus 10 años de carrera en teleSUR, dos acontecimientos la han marcado profundamente: el golpe de Estado de Honduras (junio de 2009) y la partida física del Comandante Hugo Chávez."Para todo el equipo de teleSUR fue la cobertura que nunca quisimos hacer y que más impacto emocional nos generó".</p>', '<a href="https://twitter.com/marayirateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/marayirateleSUR" target="_blank">@marayirateleSUR</a>');

var equipo6 = new Array('<div class="mheredia"></div>','Marcela Heredia', 'Presentadora del programa Impacto Econ&oacute;mico', '<p>Marcela Heredia es una profesional de la Comunicación Social y locutora nacida en Capital Federal, Argentina. El periodismo siempre representó para ella la lucha por la verdad y un camino de esperanza, en un mundo que considera una verdadera quimera.Quiso trabajar en teleSUR desde que supo que el Comandante Hugo Chávez lo tenía proyectado."Participé de un casting populoso, en Lanus (Argentina), segura de que era mi ventana para aprender una nueva forma de llevar las noticias al mundo. Por eso suelo usar la frase: teleSUR, la ventanita que nos une. Gracias a Dios, Gracias a Chávez". </p>', '<a href="https://twitter.com/marcelateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/marcelateleSUR" target="_blank">@marcelateleSUR</a>');

var equipo7 = new Array('<div class="lfblandon"></div>','Luis Francisco Bland&oacute;n', 'Presentador de noticias y programas informativos', '<p>Luis F. Blandón es periodista egresado de la Universidad Bicentenaria de Aragua (UBA), en Venezuela y se especializa en Economía Latinoaméricana. La oportunidad de ver en teleSUR las historias que los grandes medios ocultan, además de que sean contadas desde una perspectiva latinoamericana, lo impulsó a ingresar a la multiestatal."Me di cuenta que el gran servicio ofrecido por teleSUR a nuestros pueblos es presentar esa realidad, una realidad de América Latina de la que no se habla en los medios tradicionales".</p>', '<a href="https://twitter.com/LuisteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/LuisteleSUR" target="_blank">@LuisteleSUR</a>');

var equipo8 = new Array('<div class="rromero2"></div>','Ruperto Romero', 'Presentador de Deportes teleSUR', '<p>El amor al deporte y la emoción de transmitir un gol en la televisión llevó a Ruperto Romero a estudiar Comunicación Social en la Universidad Santa María, ubicada en Caracas."Trabajo en teleSUR porque me da la oportunidad de apoyar, con mi trabajo, el esfuerzo de nuestros atletas latinoamericanos (...) porque la historia de esos atletas que superan barreras sociales, raciales y cualquier tipo de discriminación,merece ser contada".Cubrió el Mundial de Fútbol Brasil 2014, un verdadero reto.</p>', '<a href="https://twitter.com/RupertoteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/RupertoteleSUR" target="_blank">@RupertoteleSUR</a>');

var equipo9 = new Array('<div class="ccweddle"></div>','Cody Weddle', 'Presentador del programa From the South', '<p>Cody Weddle llega a teleSUR y a Venezuela desde el suroeste del estado de Virginia, Estados Unidos, donde creció en un pueblo ubicado en los Montes Apalaches. Cuenta con estudios de Comunicación y Ciencias Políticas en el Virginia Tech. Anteriormente trabajaba como reportero y presentador para un canal afiliado de noticias locales en EE.UU.La gente, la cultura y la política de América Latina siempre han fascinado a Cody. Estudió español en la universidad y tuvo la oportunidad de vivir y estudiar durante un semestre en Quito, Ecuador. Pocos años más tarde volvería a Quito dónde se enteró que el nuevo proyecto de teleSUR en inglés había ubicado su sede principal. Lo llamaron para una entrevista laboral y ahora trabaja como presentador del programa "From the South" (Desde el Sur); allí hace analiza las noticias más importantes de América Latina y del mundo.Gracias sus estudios y a su interés en el periodismo, llegó a darse cuenta que América Latina se había convertido en uno de los lugares donde los periodistas se comprometen abiertamente con la ética tradicional del periodismo. Muy a menudo, los reportes y artículos no reflejan la realidad para los latinoamericanos. Cody espera que el proyecto de teleSUR en inglés ofrezca una perspectiva más auténtica de América Latina para el mundo angloparlante</p>', '<a href="https://twitter.com/CodyWteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/CodyWteleSUR" target="_blank">@CodyWteleSUR</a>');

var equipo10 = new Array('<div class="analuciacordova2"></div>','Lucía Cordova', 'Presentadora de noticias teleSUR', '<p>Lucía Córdova es una comunicadora social venezolana que posee una amplia experiencia en radio y TV; tuvo la oportunidad de acompañar las coberturas nacionales e internacionales del presidente venezolano Hugo Chávez. Es miembro fundador y editora en jefe del portal de información política La Iguana. Para esta periodista, TeleSUR es, "en esta etapa viva de nuestra historia, la más importante ventana para mostrar los rostros y decir la verdad de los pueblos del mundo, esa que ocultan las transnacionales de la información. Formar parte de este equipo de profesionales, heroico desde sus inicios, es un privilegio y una oportunidad de oro que jamás desaprovecharé".</p>', '<a href="https://twitter.com/luciateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/luciateleSUR" target="_blank">@luciateleSUR</a>');

var equipo11 = new Array('<div class="mfox"></div>','Michael Fox', 'Presentador de Imaginary Lines', '<p>Antes de incorporarse a teleSUR, Michael Fox trabajó en América Latina como editor, organizador comunitario, periodista freelance, reportero de radio, y documentalista durante una década, aproximadamente. Fox es exeditor de la revista NACLA Reporte sobre las Américas, asimismo fue director de dos documentales y coautor de dos libros sobre América Latina.</p>', '<a href="https://twitter.com/mfox_us" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/mfox_us" target="_blank">@mfox_us</a>');

var equipo12 = new Array('<div class="rdesvignes"></div>','Reagan Des Vignes', 'Presentador teleSUR Inglés', '<p>Reagan des Vignes es un productor director y presentador caribeño de televisión; ha trabajado principalmente en Barbados, Granada y Trinidad y Tobago. Actualmente, es estudiante de Periodismo en la Universidad del Caribe, COSTAATT, una de las más importantes para el periodismo en el área caribeña. Cuando no está detrás o delante de una cámara, podemos encontrarlo escalando montañas o saltando cascadas. Reagan decidió integrarse al proyecto de teleSUR para obtener una mejor comprensión de la economía, la política y la sociología de la región.</p>', '<a href="https://twitter.com/dreevay" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/dreevay" target="_blank">@dreevay</a>');

var equipo13= new Array('<div class="paoperez"></div>','Paola Perez', 'Presentadora de noticias teleSUR', '<p>Paola Pérez es periodista y abogada con Licenciatura en Ciencias Políticas y Jurídicas en la Universidad San Francisco Xavier de Chuquisaca, ubicada en la Capital del Estado Plurinacional de Bolivia. Los momentos cruciales que ha vivido, tales como la elaboración de la Constitución de su país, la inclusión de los sectores más oprimidos en esferas de poder y la consolidación de la igualdad, dignidad y soberanía, han hecho que la comunicación se convierta en su pasión para llevar, desde los lugares más remotos, la verdad de los que hace unos años eran invisibilizados por los grandes monopolios comunicacionales. Ha tenido la oportunidad de entrevistar a líderes de la región, en reiteradas oportunidades, por ejemplo a los presidentes Evo Morales y Rafael Correa. “Trabajar en TeleSUR significa para mí un compromiso de vida, de principios, de razón que concluyen en un solo objetivo ‘la verdad’ que merecen nuestros pueblos. Es un honor formar parte de este valioso equipo”.</p>', '<a href="https://twitter.com/PaolateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/PaolateleSUR" target="_blank">@PaolateleSUR</a>');

var equipo14= new Array('<div class="gsilva"></div>','Gabriel Silva', 'Presentador de Deportes teleSUR', '<p>Gabriel Silva es periodista egresado de la Universidad de Santa Rosa de Lima en Caracas, Venezuela. Desde muy joven sintió pasión por el deporte y admiración por los presentadores que, con entusiasmo, informaban de diferentes deportes a través de los medios de comunicación. Después de graduarse, el destino lo puso en el camino de lo que considera la mejor fuente en Periodismo: deportes. teleSUR le dio la bienvenida para que pudiera mantener vivo su sueño de trabajar para informar sobre el acontecer deportivo a América Latina, tierra de grandes atletas.</p>', '<a href="https://twitter.com/DeportesTeleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/DeportesTeleSUR" target="_blank">@DeportesTeleSUR</a>');

var equipo15= new Array('<div class="yosvany"></div>','Yosvany Noguet', 'Presentador de noticias teleSUR', '<p>Yosvany Noguet trabajó como corresponsal de teleSUR en Egipto desde 2013 hasta convertirse en presentador de noticias del canal en septiembre de 2015. Yosvany es egresado de la Universidad de la Habana, Cuba y desde 1997 ejerce la profesión de comunicador; posee un máster en Dirección de Programas Informativos para TV y realizó un Diplomado en Periodismo, Estudios Sociales y Derecho Internacional Humanitario. Para Yosvany “comunicar es un reto que asumimos cada día por ello hay que estar preparado siempre, incluso en las horas de descanso”.</p>', '<a href="https://twitter.com/YosvanyteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/YosvanyteleSUR" target="_blank">@YosvanyteleSUR</a>');



var equipos= new Array (14);
			equipos[0] = equipo1;
			equipos[1] = equipo2;
			equipos[2] = equipo3;
			equipos[3] = equipo4;
			equipos[4] = equipo5;
			equipos[5] = equipo6;
			equipos[6] = equipo7;
			equipos[7] = equipo8;
			equipos[8] = equipo9;
			equipos[9] = equipo10;
			equipos[10] = equipo11;
			equipos[11] = equipo12;
			equipos[12] = equipo13;
			equipos[13] = equipo14;	
			equipos[14] = equipo15;					
contadorEquipos = equipos.length-1;