var equipo1= new Array('<div class="pvillegas"></div>','Patricia Villegas', 'President of teleSUR', '<p>Patricia Villegas was born in Cali, the third-largest city in Colombia. She began working at the multistate news organization as a news and current affairs presenter and is one of the founders of teleSUR. Today, she is the president of the organization. Villegas decided to be a journalist because she wanted to change the world.<br><br>“I work to make visible the realities of the people who are not seen … We work with passion, honesty, seeking with rigour and respect, to share the reality of our Latin American and Caribbean compatriots. We are on this land, we are part of it, we do journalism for our America.”</p>', '<a href="https://twitter.com/pvillegas_tlSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/pvillegas_tlSUR" target="_blank">@pvillegas_tlSUR</a>'); 

var equipo2 = new Array('<div class="aistillarte"></div>','Abraham Istillarte', 'News Anchor and informative programs', '<p>Abraham Istillarte is a Venezuelan journalist and graduate of the University of Zulia. He extended his education with a Master of Latin American Studies in the Pontificia University Javeriana in Bogota, Colombia.<br><br>When he heard Fidel Castro and Hugo Chavez speak of the need to create an independent Latin American media organization that would break the monopoly of the big transnational media corporations, he did everything he could to join the project and was welcomed in.<br><br>“I have been here from when there were no more than 15 people, when there was no signal on air. I helped launch our signal.”<br><br>For Istillarte, those who attack teleSUR are trying to silence the voice of the people in defending their rights and sharing their truth.</p>', '<a href="https://twitter.com/abrahamteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/abrahamteleSUR" target="_blank">@abrahamteleSUR</a>'); 
 
var equipo3 = new Array('<div class="tperez"></div>','Tatiana Perez', 'News and informative shows anchor', '<p>Tatiana Perez was born in Colombia and graduated in journalism from the Autonomous Occident University in Cali.<br><br>The desire to tell and report stories, like those of the armed conflict in Colombia, prompted her to work in communications. <br><br>“I work at teleSUR for its heart and righteousness. Its firm beliefs in carrying out responsible, rigorous journalism, keeping to the truth and the reality. These are not principles you find easily in any other media organization.”<br><br>The NATO war against Libya, the release of hostages by the Revolutionary Armed Forces of Colombia and the coup against Manuel Zelaya in Honduras have impacted her way of seeing the world and of conducting journalism.<br><br></p>', '<a href="https://twitter.com/tatianateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/tatianateleSUR" target="_blank">@tatianateleSUR</a>'); 

var equipo4 = new Array('<div class="rgomez"></div>','Rey G&oacute;mez', 'News and informative shows anchor', '<p>Rey Gomez is a Cuban journalist and teleSUR news presenter. He has a Bachelor Degree in Spanish and Literature but chose communication as a career due to the influence of his brother, who is a journalist. <br><br>Gomez has always been interested in international politics and community integration processes.<br><br>“Our program has achieved wide acceptance. Wherever I go, I am identified as a presenter of the channel. Some might not know my name but they affectionately call out ‘way to go teleSUR’.”</p>', '<a href="https://twitter.com/ReyGomeztlSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/ReyGomeztlSUR" target="_blank">@ReyGomeztlSUR</a>');

var equipo5 = new Array('<div class="mchirinos"></div>','Marayira Chirinos', 'News and informative shows anchor', '<p>Marayira Chirinos is a graduate of political science from the Central University of Venezuela (UCV) but has adopted journalism as her second profession.<br><br>From the moment she heard the leader of the Bolivarian Revolution Hugo Chavez speak about the urgent need to create teleSUR as a way to democratize communication in Latin America, she felt completely identified with the project.<br><br>“I felt that it would change the history of communication in the region and in the world. With a great deal of pride I can say that it has achieved this and in the first go.”<br><br>She believes teleSUR as a media organization shares the reality of Latin America and the world from eyes of the people. “It is journalism that is committed to local stories, to those stories nobody tells.” In her 10-year career, two highlights stand out: the coup in Honduras (June, 2009) and the death of Hugo Chavez. “For the entire team at teleSUR this was the news we never wanted to cover and what had the greatest emotional impact on us.”</p>','<a href="https://twitter.com/marayirateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/marayirateleSUR" target="_blank">@marayirateleSUR</a>');

var equipo6 = new Array('<div class="mheredia"></div>','Marcela Heredia', 'Program Presenter,<br/>Economic Impact', '<p>Marcela Heredia is a communications professional and commentator born in Buenos Aires, Argentina. For her, journalism has always represented the fight for the truth and the path of hope in a world filled with illusion. She wanted to work with teleSUR from the moment Hugo Chavez proposed it. “I took part in a public casting in Lanus (Argentina). I was sure this was my window to learn a new way of bringing news to the world. That’s why I usually use the phrase: teleSUR  a small window that brings us together. Thanks to God and thanks to Chavez.”</p>', '<a href="https://twitter.com/marcelateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/marcelateleSUR" target="_blank">@marcelateleSUR</a>');

var equipo7 = new Array('<div class="lfblandon"></div>','Luis Francisco Bland&oacute;n', 'News and informative shows anchor', '<p>Luis F. Blandon is a journalist graduate from the Bicentenary University of Aragua (UBA) in Venezuela, specializing in Latin American economics. The opportunity to see teleSUR give space to the stories big media companies had hidden, and to see them told from a Latin American perspective inspired him to join the multi-state team.<br><br>“I realized that the great service offered by teleSUR to our people is to present reality, the real Latin America that is not spoken about in traditional media.”</p>', '<a href="https://twitter.com/LuisteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/LuisteleSUR" target="_blank">@LuisteleSUR</a>');

//var equipo8 = new Array('<div class="earellano"></div>','Edgardo Arellano', 'TeleSUR Sports Presenter', '<p>Edgardo Arellano is a communications graduate, specializing in audiovisual journalism, from Santa Maria University in Caracas. Having grown up playing sports, Arellano decided to focus on sports journalism. “It gave me the opportunity to stay connected to the discipline and work with what I enjoyed.”<br><br>For Arellano, teleSUR provides “first hand reporting and an option to see the other side of the coin.”<br><br>His experience at this international channel has taken him to two important sporting events: the World Cup in South Africa in 2010 and the Beijing Olympic Games in 2008, the most important events he has covered in his journalism career.</p>', '<a href="https://twitter.com/arellanoteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/arellanoteleSUR" target="_blank">@arellanoteleSUR</a>');

var equipo8 = new Array('<div class="rromero2"></div>','Ruperto Romero', 'TeleSUR&rsquo;s Sports Anchor', '<p>Love for sport and the emotion of broadcasting a goal on television inspired Ruperto Romero to study social communication at Santa Maria University in Caracas. “I work at teleSUR because it gives me the opportunity to support, with my work, the effort of our Latin American athletes… because the stories of these athletes, who transcend social and racial barriers along with other types of prejudice, deserve to be told.” He covered the World Cup in Brazil in 2014.</p>', '<a href="https://twitter.com/RupertoteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/RupertoteleSUR" target="_blank">@RupertoteleSUR</a>');

var equipo9 = new Array('<div class="ccweddle"></div>','Cody Weddle', 'Anchor From the South', '<p>Cody Weddle came to teleSUR and Venezuela from the Appalachian Mountain in the state of Virginia, United States. He studied communications and political sciences at Virginia Tech and worked in his country as a reporter and presenter for a local news channel. Cody has always been interested in people, culture and Latin American politics. He studied Spanish at university and had the opportunity to live and study a semester in Quito, Ecuador.<br><br>Years later, Cody returned to Quito and it was here that he was interviewed for a position with teleSUR´s new project: an English-language website. Now, he is the presenter of From the South, a program that analyzes the most important news from Latin America and the world.<br><br> Cody hopes that teleSUR English will offer a more authentic perspective of Latin America for the English-speaking world. </p>', '<a href="https://twitter.com/CodyWteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/CodyWteleSUR" target="_blank">@CodyWteleSUR</a>');

var equipo10 = new Array('<div class="analuciacordova2"></div>','Lucía Cordova', 'Anchor teleSUR news', '<p>Lucia Cordova is a Venezuelan journalist with extensive experience in radio and television. She had the opportunity to present national and international coverage of the Venezuelan President Hugo Chavez. She is a founding member and editor in chief of the online political journal La Iguana. For Lucia, teleSUR is “in a vibrant stage of our history, it is the most important window to show the faces of the community and to tell the truth of the people to the world, a truth that is hidden by transnational media corporations. Being part of this team of professionals, who have been heroic from the start, is a privilege and a golden opportunity that I will never take for granted.””<p>', '<a href="https://twitter.com/luciateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/luciateleSUR" target="_blank">@luciateleSUR</a>');

var equipo11 = new Array('<div class="mfox"></div>','Michael Fox', 'Host of Imaginary Lines', '<p>For a decade, Michael Fox has worked in Latin America as an editor, community organizer, and documentary film maker. Also, Fox was the editor of the magazine NACLA Reporting on the Americas, as well as the director of two documentaries and co-author of two books about Latin America.  He started in teleSUR since the launch of the English-language website in 2014, where he has been the coordinator and the presenter of the show Imaginary Lines.</p>', '<a href="https://twitter.com/mfox_us" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/mfox_us" target="_blank">@mfox_us</a>');

var equipo12 = new Array('<div class="rdesvignes"></div>','Reagan Des Vignes', 'teleSUR English  Presenter ', '<p>Reagan Des Vignes is a producer, director and presenter of Caribbean television. He has worked principally in Barbados, Grenada and Trinidad and Tobago. Today he is studying journalism at the University of the Caribbean, COSTATT, in one of the most important journalism courses offered in the Caribbean. When he is not in front of or behind the camera, you can find him climbing mountains or scaling down waterfalls. Reagan decided to join teleSUR to better his understanding of regional economics, politics and sociology.</p>', '<a href="https://twitter.com/dreevay" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/dreevay" target="_blank">@dreevay</a>');

var equipo13 = new Array('<div class="paoperez"></div>','Paola Perez', 'Anchor teleSUR news', '<p>Paola Perez is a journalist and lawyer with a Bachelor of Political and Judicial Sciences from the University of San Francisco Xavier in Chuquisaca, in the capital of the Plurinational State of Bolivia. Living through crucial historical moments, such as the creation of the Bolivian constitution, the inclusion of the most oppressed sectors of society into the spheres of power and the consolidation of equality, dignity and sovereignty, transformed communication into a passion to bring, from the most remote places in the world, the truth of what has been made invisible over the years by big media monopolies. Perez has had numerous opportunities of interview leaders from region, including presidents Evo Morales and Rafael Correa. “To me working with teleSUR is a commitment for life, a commitment to principles and what is right, that all builds towards one goal: the truth that our communities deserve to know. It is an honor to be part of this valiant team.”  </p>', '<a href="https://twitter.com/PaolateleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/PaolateleSUR" target="_blank">@PaolateleSUR</a>');

var equipo14= new Array('<div class="gsilva"></div>','Gabriel Silva', 'teleSUR Sports Presenter', '<p>Gabriel Silva is a journalist graduate from Santa Rosa Catholic University in Caracas, Venezuela. From a young age, he felt passion for sport and admiration for sport presenters who, with their enthusiasm, reported on different sports in the media. After graduating, Silva began to work towards what he believed was the best field of journalism: Sports. teleSUR welcomed him to the team and enabled him to keep fulfill his dream of reporting on sport updates in Latin America, the land of great athletes.</p>', '<a href="https://twitter.com/DeportesTeleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/DeportesTeleSUR" target="_blank">@DeportesTeleSUR</a>');

var equipo15= new Array('<div class="yosvany"></div>','Yosvany Noguet', 'teleSUR news Presenter', '<p>Yosvany Noguet worked as teleSUR’s Egypt correspondent from 2013 before becoming in one of the channel’s news presenter in September, 2015. Yovany is a graduate of the University of Havana, Cuba and from 1997 has worked professionally in media and communications. He has a Master of Program Management for TV and a Diploma in Journalism, Social Science and International Humanitarian Law. For Yosvany, “reporting is the challenge we take on each day. To do this, we must always be prepared even in our work breaks.”</p>', '<a href="https://twitter.com/YosvanyteleSUR" target="_blank" class="reporterRedes"><img alt="" src="/arte/about/alcanceTw.jpg" /></a>', '<a class="userTwitter" href="https://twitter.com/YosvanyteleSUR" target="_blank">@YosvanyteleSUR</a>');


var equipos= new Array (14);
			equipos[0] = equipo1;
			equipos[1] = equipo2;
			equipos[2] = equipo3;
			equipos[3] = equipo4;
			equipos[4] = equipo5;
			equipos[5] = equipo6;
			equipos[6] = equipo7;
			equipos[7] = equipo8;
			equipos[8] = equipo9;
			equipos[9] = equipo10;
			equipos[10] = equipo11;
			equipos[11] = equipo12;
			equipos[12] = equipo13;
			equipos[13] = equipo14;
			equipos[14] = equipo15;	
contadorEquipos = equipos.length-1;